noun1 = input("noun1")
state = input("state")
verb1 = input("verb1")
noun3 = input("noun3")
peoplename = input("peoplename")
verb2 = input("verb2")
noun4 = input("noun4")
verb3 =("verb3")
noun5 = ("noun5")
partofbody = ("partofbody")
adjective1 = input("adjective1")
print("A" , noun1 , "in" , state, "was arrested this morning after he" , verb1, "a in front of a", noun3, peoplename, ",had a history of" , verb2, ",but no one-not even his", peoplename, "ever imagined he'd", verb2, "with a", noun4, "stuck in his" , partofbody)  
